.default_tag: &default_tag
  tags:
    - backend-docker-large
  image: docker.phonepe.com:5000/pp-maven:3.8.4-openjdk-11
  before_script:
    - export MAVEN_OPTS="--add-opens java.base/java.lang=ALL-UNNAMED"

stages:
  - build
  - test
  - deploy
  - release

compile:
  stage: build
  <<: *default_tag
  script:
    - mvn -U compile
  except:
    - master
    - develop

quality:
  stage: test
  <<: *default_tag
  script:
    - mvn clean verify -U -Pquality_check
  except:
    - master
    - develop
    - stage

deploy:
  stage: deploy
  <<: *default_tag
  script:
    - mvn clean deploy -U -DskipTests
  only:
    refs:
      - stage

release:
  stage: release
  <<: *default_tag
  script:
    - git remote set-url origin "git@gitlab.phonepe.com:${CI_PROJECT_PATH}.git"
    - git checkout master
    - git pull
    - git checkout develop
    - git pull
    - mvn -U jgitflow:release-start jgitflow:release-finish
    - git push --all
    - git push --tags origin
  when: manual
  only:
    refs:
      - develop